# Este é um template Mako usado pelo Alembic para gerar scripts de migração de banco de dados.
# Ele define a estrutura para gerenciar a evolução do esquema do banco de dados de forma controlada.

"""add telegram_mensagem
# Descrição da migração, fornecida pelo desenvolvedor.

Revision ID: a608bad9f094
# Identificador único para esta migração, crucial para o controle de versão do esquema.
Revises: e01134c03379
# Identificador da migração anterior, estabelecendo a ordem das migrações.
Create Date: 2025-11-17 12:19:09.711206
# Data e hora da criação desta migração.

"""
from alembic import op
# 'op' fornece operações de banco de dados (DDL) para modificar o esquema.
import sqlalchemy as sa
# 'sa' (SQLAlchemy) é usado para definir tipos de dados e construções de esquema.


# Identificadores de revisão, usados pelo Alembic para rastrear o histórico.
revision = 'a608bad9f094'
# O ID da revisão atual.
down_revision = 'e01134c03379'
# O ID da revisão para a qual esta migração reverte.
branch_labels = None
# Rótulos de ramificação, úteis para migrações em ambientes de desenvolvimento paralelos.
depends_on = None
# Dependências de outras migrações, garantindo a ordem de execução.


def upgrade():
    # A função 'upgrade' é responsável por aplicar as mudanças no esquema do banco de dados.
    # Ela contém as operações DDL (Data Definition Language) que evoluem o banco de dados
    # para a próxima versão.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TelegramMensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['Chamado.chamado_ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # A função 'downgrade' é responsável por reverter as mudanças aplicadas pela função 'upgrade'.
    # É essencial para a reversibilidade do esquema, permitindo desfazer migrações
    # em caso de erros ou necessidade de retornar a um estado anterior.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TelegramMensagem')
    # ### end Alembic commands ###
